### ISSUE TITLE
seen / seen_pos

### ISSUE THREAD

**Issue by wiedehopf** [alphafox02/TAR1090ToTAK#2]
https://github.com/alphafox02/TAR1090ToTAK/blob/a2712707fd1a626dded7b4db7ec3ad33e786ca59/TAR1090ToTAK.py#L244C34-L244C50

https://github.com/wiedehopf/readsb/blob/dev/README-json.md
```
seen_pos: how long ago (in seconds before "now") the position was last updated
seen: how long ago (in seconds before "now") a message was last received from this aircraft
```

Use as you see fit.

**Comment by wiedehopf** [comment]
```py
                alt_baro = aircraft.get('alt_baro', 0)
```
Defaulting to zero seems like a bad choice.

**Comment by alphafox02** [comment]
Tried to make some adjustments for each thing you mentioned. 

https://github.com/alphafox02/TAR1090ToTAK/commit/c608d7892e5524449e4323f6b907d0411aeb3091
